/**
 * InitialState - Default application state for the admin panel.
 */

export function createInitialState() {
    return {
        connected: false,
        patterns: [],
        currentPattern: null,
        currentPreset: 'auto',
        bands: [0, 0, 0, 0, 0, 0],
        amplitude: 0,
        isBeat: false,
        beatIntensity: 0,
        frame: 0,
        bandSensitivity: [1, 1, 1, 1, 1, 1],
        masterSensitivity: 1,
        attack: 0.35,
        release: 0.08,
        agcMaxGain: 8,
        beatSensitivity: 1,
        beatThreshold: 1.3,
        blockCount: 16,
        blackout: false,
        freeze: false,
        particleEffects: [],
        enabledParticleEffects: new Set(),
        particleGlobalIntensity: 1.0,
        djRoster: [],
        activeDJ: null,
        pendingDJs: [],
        minecraftConnected: false,
        minecraftServerType: null,
        connectCodes: [],
        stages: [],
        selectedStage: null,
        selectedZones: new Set(),
        zonePatterns: {},
        zone: {
            name: 'main',
            entityCount: 16,
            blockType: 'SEA_LANTERN',
            baseScale: 0.5,
            maxScale: 1.0,
            brightness: 15,
            interpolation: 2,
            glowOnBeat: false,
            dynamicBrightness: false,
            sizeX: 10,
            sizeY: 10,
            sizeZ: 10,
            rotation: 0,
            showBpm: false,
            showPattern: false,
            showBands: false,
            renderMode: 'entities',
            particleViz: {
                particleType: 'DUST',
                density: 3,
                colorMode: 'frequency',
                fixedColor: '#00ffff',
                particleSize: 1.5,
                trail: false
            }
        },
        bandMaterials: [null, null, null, null, null],
        bandMaterialsSource: 'default',
        voiceChat: {
            statusReceived: false,
            available: false,
            streaming: false,
            enabled: false,
            channelType: 'static',
            distance: 100,
            connectedPlayers: 0
        },
        bitmap: {
            initialized: false,
            initializedZones: new Set(),
            zones: {},
            zone: 'main',
            width: 16,
            height: 12,
            patterns: [],
            transitions: [],
            palettes: [],
            activePattern: null,
            activePalette: null,
            brightness: 100,
            strobe: false,
            frozen: false,
            dataFetched: false,
        },
        entities: [],
        zoneEntities: {},
        scenes: [],
        currentScene: null
    };
}
