/* eslint-disable @typescript-eslint/no-explicit-any */

/** Pre-bundled fengari browser module (generated by scripts/bundle-fengari.mjs) */
export const to_luastring: (s: string) => Uint8Array;
export const lua: any;
export const lauxlib: any;
export const luaopen_base: any;
export const luaopen_math: any;
export const luaopen_string: any;
export const luaopen_table: any;
export const luaopen_coroutine: any;
export const luaopen_utf8: any;
