/* eslint-disable @typescript-eslint/no-explicit-any */

/** Pre-bundled fengari browser module (generated by scripts/bundle-fengari.mjs) */
declare const fengari: {
  to_luastring: (s: string) => Uint8Array;
  lua: any;
  lauxlib: any;
  luaopen_base: any;
  luaopen_math: any;
  luaopen_string: any;
  luaopen_table: any;
  luaopen_coroutine: any;
  luaopen_utf8: any;
};
export default fengari;
